# Generated by Django 4.2.5 on 2023-10-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='duracion',
        ),
    ]
