# Generated by Django 4.2.5 on 2023-10-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0005_remove_comunicado_publicado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='fecha_ultima_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
