# Generated by Django 4.2.5 on 2023-10-22 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0009_comunicado_publicado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='publicado_por',
        ),
    ]
