# Generated by Django 4.2.5 on 2023-10-22 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comunicados', '0010_remove_comunicado_publicado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
