# Generated by Django 4.2.5 on 2023-10-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0011_comunicado_creado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='creado_por',
        ),
    ]
